title: Harsha K
#logo
description: Post grad | Dr. BR Ambedkar National Institute of Technology Jalandhar
description: Grad | National Institute of Technology Karnataka Surathkal
theme: jekyll-theme-minimal
